dist: focal
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-1"
  env: "Docker-react-1-env"
  bucket_name: "elasticbeanstalk-eu-north-1-365255307003"
  bucket_path: "docker-react-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
